### ISSUE TITLE
Constructor tactic missing

### ISSUE THREAD

**Issue by ThijsVromen** [djvelleman/STG4#13]
The constructor tactic is mentioned several times in the level descriptions (e.g. lvl5 of the intersection world). And when I use it, it indeed works as described. It is however missing from the tactic overview.:
![Screenshot from 2024-07-12 21-14-57](https://github.com/user-attachments/assets/f61c89b0-bef4-4ce6-8a07-74a6b7bfceb6)
To make the tactic more intuitively usable, it would be great if it is added to the overview.

**Comment by snoeyink** [comment]
Looks like constructor, right, left, were added by last week's commit.  (I see all three using the simple browser within VSCode)

**Comment by djvelleman** [comment]
Yes, they've been added.  So I'll close this issue.
